# Generated by Django 4.1.13 on 2024-08-16 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_branch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
