# Generated by Django 4.1.13 on 2024-08-19 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
        ('user', '0007_delete_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='requested_for',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='branch.branch'),
            preserve_default=False,
        ),
    ]
