# Generated by Django 4.1.13 on 2024-08-29 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_ticket_requested_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
