# Generated by Django 4.1.13 on 2024-08-29 02:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_ticket_ticket_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='comments',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
