# Generated by Django 4.1.13 on 2024-08-29 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_ticket_comments_alter_ticket_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='requested_for',
            new_name='requested_branch',
        ),
    ]
