# Generated by Django 4.1.13 on 2024-09-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_rename_requested_for_ticket_requested_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='estimated_completion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='requested_branch',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
